require 'test/unit'
require 'rubygems'
require 'mocha'
require 'logger'
require 'ruby-debug'

require File.dirname(__FILE__) + '/../../lib/weatherzone'

require 'weatherzone/resources/point_forecast'
require 'weatherzone/resources/forecast'
require 'weatherzone/resources/conditions'
require 'weatherzone/resources/district_forecast'
require 'weatherzone/resources/state_forecast'
require 'weatherzone/resources/marine_summary'
require 'weatherzone/resources/marine_forecast'
require 'weatherzone/resources/surf_report'
require 'weatherzone/resources/camera'
require 'weatherzone/resources/lift'
require 'weatherzone/resources/snow_report'
require 'weatherzone/resources/historical_observation'
require 'weatherzone/resources/daily_observation'
require 'weatherzone/resources/climate_period'
require 'weatherzone/resources/warning'
require 'weatherzone/resources/image'
require 'weatherzone/resources/almanac_period'
require 'weatherzone/resources/almanac'
require 'weatherzone/resources/tide'
require 'weatherzone/resources/buoy_observation'
require 'weatherzone/resources/location'
require 'weatherzone/resources/country'
require 'weatherzone/resources/moon_phase'
require 'weatherzone/resources/news_item'
require 'weatherzone/resources/weather'
